/**
 * Emitter: Figma-inventory pack object → a Nib design-system pack directory.
 *
 * Consumes the artifact produced by the `figma-inventory` workflow (or a
 * hand-authored equivalent) and writes the pack files that core/packs/loader.js
 * and docs/Design-System-Packs.md expect:
 *
 *   <out>/pack.json           <out>/theme.js        <out>/tokens.css
 *   <out>/design-system.json  <out>/figma-map.json
 *
 * Output JS is plain ES5/var-style (no bundler; loaded via <script>), matching
 * core/ingest/emit.js. For a PROPRIETARY system, point --out at the private
 * pack repo (e.g. nib-eqds), never at public Nib.
 *
 * CLI:
 *   node tools/figma-inventory/emit.js <input.json> --out <dir> [--id <id>] [--name <name>] [--version <v>]
 *
 * <input.json> shape (extra keys ignored):
 *   {
 *     id?, name?, version?,
 *     designSystem | design : { meta, tokens, components, patterns, styles, conventions },
 *     theme                  : { label, font, fontUrl?, tokens:{ "--wf-*": "#.." } },
 *     figmaMap | figma       : { variables, components, recreationRules, overrides }
 *   }
 */

const fs = require('fs');
const path = require('path');

const NIB_CONTRACT = '1.0';

function ensureDir(p) { fs.mkdirSync(p, { recursive: true }); }
function readJson(p) { return JSON.parse(fs.readFileSync(p, 'utf8')); }
function writeFile(dir, name, content) {
  const target = path.join(dir, name);
  fs.writeFileSync(target, content);
  return target;
}

function jsLiteral(value) { return JSON.stringify(value, null, 2); }

/** :root { --token: value; } from a flat token map. */
function tokensToCss(tokens, label) {
  const entries = Object.entries(tokens || {});
  const head = `/* ${label} pack — static token fallback. Mirror of theme.js tokens.\n` +
    `   Load AFTER core/proto-tokens.css. JS theme path is preferred. */\n`;
  if (!entries.length) return head + ':root {\n}\n';
  const lines = entries.map(([k, v]) => `  ${k}: ${v};`).join('\n');
  return head + `:root {\n${lines}\n}\n`;
}

/** window.NIB_PACKS[id] = { ...theme... } registration script. */
function themeJs(id, label, theme) {
  const pack = {
    id: id,
    label: label,
    nibContract: NIB_CONTRACT,
    theme: theme,
    figmaMapUrl: 'figma-map.json',
  };
  return `/* ${label} pack — theme registration (theme.js).\n` +
    `   Registers window.NIB_PACKS['${id}'] for core/packs/loader.js.\n` +
    `   Load BEFORE core/packs/loader.js. Generated by tools/figma-inventory/emit.js. */\n` +
    `window.NIB_PACKS = window.NIB_PACKS || {};\n` +
    `window.NIB_PACKS[${JSON.stringify(id)}] = ${jsLiteral(pack)};\n`;
}

function parseArgs(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') out.out = argv[++i];
    else if (a === '--id') out.id = argv[++i];
    else if (a === '--name') out.name = argv[++i];
    else if (a === '--version') out.version = argv[++i];
    else out._.push(a);
  }
  return out;
}

function emit(input, opts) {
  const outDir = opts.out;
  if (!outDir) throw new Error('emit: --out <dir> is required');

  const design = input.designSystem || input.design || {};
  const theme = input.theme || {};
  const figmaMap = input.figmaMap || input.figma || {};

  const id = opts.id || input.id || (design.meta && design.meta.system) || 'pack';
  const safeId = String(id).toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '');
  const name = opts.name || input.name || (design.meta && design.meta.system) || safeId;
  const version = opts.version || input.version || '1.0.0';
  const label = theme.label || name;

  // Stamp contract into the inventory meta.
  design.meta = Object.assign({}, design.meta, { nibContract: NIB_CONTRACT });
  if (!figmaMap.meta) figmaMap.meta = {};
  figmaMap.meta = Object.assign({ system: name, nibContract: NIB_CONTRACT }, figmaMap.meta);

  const packJson = {
    id: safeId,
    name: name,
    version: version,
    nibContract: NIB_CONTRACT,
    exports: {
      theme: 'theme.js',
      tokens: 'tokens.css',
      inventory: 'design-system.json',
      figmaMap: 'figma-map.json',
    },
  };

  ensureDir(outDir);
  const written = [];
  written.push(writeFile(outDir, 'pack.json', jsLiteral(packJson) + '\n'));
  written.push(writeFile(outDir, 'theme.js', themeJs(safeId, label, theme)));
  written.push(writeFile(outDir, 'tokens.css', tokensToCss(theme.tokens, label)));
  written.push(writeFile(outDir, 'design-system.json', jsLiteral(design) + '\n'));
  written.push(writeFile(outDir, 'figma-map.json', jsLiteral(figmaMap) + '\n'));
  return { id: safeId, outDir, written };
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const inputPath = args._[0];
  if (!inputPath || !args.out) {
    console.error('Usage: node tools/figma-inventory/emit.js <input.json> --out <dir> [--id <id>] [--name <name>] [--version <v>]');
    process.exit(1);
  }
  const input = readJson(inputPath);
  const res = emit(input, args);
  console.log(`Emitted pack "${res.id}" → ${res.outDir}`);
  res.written.forEach((f) => console.log('  ' + path.relative(process.cwd(), f)));
}

if (require.main === module) main();

module.exports = { emit, tokensToCss, themeJs };
